Revert "[202211_SPC4_bringup] Disable automatic FW upgrade"
This reverts commit c23dc6aa4d613e3394dc2e8cd6db0b83d5bd2ab6.

diff --git a/device/mellanox/x86_64-mlnx_msn2700-r0/platform_reboot b/device/mellanox/x86_64-mlnx_msn2700-r0/platform_reboot
--- a/device/mellanox/x86_64-mlnx_msn2700-r0/platform_reboot
+++ b/device/mellanox/x86_64-mlnx_msn2700-r0/platform_reboot
@@ -28,17 +28,17 @@ function SafePwrCycle() {
 
 ParseArguments "$@"
 
-#${FW_UPGRADE_SCRIPT} --upgrade --verbose
-#EXIT_CODE="$?"
-#if [[ "${EXIT_CODE}" != "${EXIT_SUCCESS}" ]]; then
-#    echo "Failed to burn MLNX FW: errno=${EXIT_CODE}"
-#
-#    if [[ "${FORCE_REBOOT}" != "yes" ]]; then
-#        echo "Reboot is interrupted: use -f|--force to override"
-#        exit "${EXIT_ERROR}"
-#    fi
-#fi
-#
-#${PENDING_COMPONENT_FW}
+${FW_UPGRADE_SCRIPT} --upgrade --verbose
+EXIT_CODE="$?"
+if [[ "${EXIT_CODE}" != "${EXIT_SUCCESS}" ]]; then
+    echo "Failed to burn MLNX FW: errno=${EXIT_CODE}"
+
+    if [[ "${FORCE_REBOOT}" != "yes" ]]; then
+        echo "Reboot is interrupted: use -f|--force to override"
+        exit "${EXIT_ERROR}"
+    fi
+fi
+
+${PENDING_COMPONENT_FW}
 
 SafePwrCycle
